name: Bump

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - README.md
      - .github/workflows/bump.yml # self-triggering
  workflow_dispatch:

jobs:
  bump:
    permissions:
      contents: write # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write # for gr2m/create-or-update-pull-request-action to create a PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm and Install
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Get previous version
        run: |
          previous_version=$(jq -r '.version' elm.json)
          echo "previous_version=$previous_version" >> $GITHUB_ENV

      # use the elm diff output when we make the PR
      # handles multiline strings
      - name: Elm diff output
        id: step_one
        run: |
          {
            echo 'DIFF_MSG<<EOF'
            pnpm elm diff
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Run elm bump
        run: yes | pnpm elm bump
        continue-on-error: true

      - name: Get new version
        run: |
          new_version=$(jq -r '.version' elm.json)
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Run `elm-review --fix`
        run: pnpm elm-review --fix-all-without-prompt

      - name: Commit and Push to PR
        if: env.new_version != env.previous_version
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          # We cannot use the GITHUB_TOKEN here because workflows will not run when PRs are created by the GITHUB_TOKEN
          # https://stackoverflow.com/a/72451611
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          title: Bump Versions
          body: |
            ${{ env.DIFF_MSG }}

            Update version from ${{ env.previous_version }} to ${{ env.new_version }}
          branch: bump-versions
          commit-message: Bump Versions
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
