name: Auto Update

# automatically run the update script every month
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm and Install
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Autogenerate code
        run: pnpm get-colors && pnpm gen

      - name: Run `elm-review`
        run: pnpm review

      - name: Commit and push changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update colors"
          branch: update-colours

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-colours
          delete-branch: true
          title: "chore: update colors"
          # We cannot use the GITHUB_TOKEN here because workflows will not run when PRs are created by the GITHUB_TOKEN
          # https://stackoverflow.com/a/72451611
          token: ${{ secrets.GH_PAT }}
