name: Auto Update

# automatically run the update script every month
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm and Install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Autogenerate code
        run: pnpm get-colors && pnpm gen

      - name: Run `elm-review`
        run: pnpm review

      - name: Commit and push changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update colors"
