name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  elm-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm and Install
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Run `elm-review`
        run: pnpm review
